# RESHAPE

In [6]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [8]:
flattend=arr.flatten() # 2D=>1D
print(flattend,flattend.shape)

[1 2 3 4 5 6] (6,)


# INDEXING

In [ ]:
arr=np.array([1,2,3,4,5])

print(arr[0])