# RESHAPING

In [6]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [8]:
flattend=arr.flatten() # 2D=>1D
print(flattend,flattend.shape)

[1 2 3 4 5 6] (6,)


# INDEXING

In [9]:
arr=np.array([1,2,3,4,5])

print(arr[0]) #1
print(arr[2]) #3

1
3


In [16]:
arr2=np.array([[1,9,3],[4,5,6]])
print(arr2[0][2])
print(arr2[1][2])

3
6


# FANCY INDEXING

In [18]:
arr=np.array([1,2,3,4,5])
index=[0,1,3]
print(arr[index])

[1 2 4]


# BOOLEAN INDEXING

In [19]:
arr=np.array([1,2,3,4,5])

print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[3 4 5]
[2 4]
[1 3 5]


# SLICING

In [23]:
arr=np.array([1,2,3,4,5])

print(arr[1:4]) #[start : end : step]
print(arr[1:]) #[start : end : step]
print(arr[:4]) #[start : end : step]
print(arr[:]) #[start : end : step]
print(arr[::2]) #[start : end : step]

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


# COPY VS VIEW

In [24]:
nums=[1,2,3,4,5]
sub_list=nums[1:3]

print(sub_list)

sub_list[0]=77

print(sub_list)
print(nums)

[2, 3]
[77, 3]
[1, 2, 3, 4, 5]


In [27]:
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]

print(sub_arr)
sub_arr[0]=88

print(sub_arr)
print(arr)

[2 3]
[88  3]
[ 1 88  3  4  5]


In [28]:
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3].copy()

print(sub_arr)
sub_arr[0]=88

print(sub_arr)
print(arr)

[2 3]
[88  3]
[1 2 3 4 5]
