In [2]:
import numpy as np

In [4]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [5]:
sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)

[12 15 18]


In [6]:
sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

[ 6 15 24]


In [7]:
print(arr2D[0:2 , 1:2])

[[2]
 [5]]
