In [4]:
import numpy as np

# Vectorization

In [5]:
arr=np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


In [6]:
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr+arr2)

[ 7  9 11 13 15]


# Broadcasting

In [7]:
arr1=np.array([1,2,3,4,5])
print(arr+5)

[ 6  7  8  9 10]


In [10]:
arr1D=np.array([1,2,3,4,5])
arr2D=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr1D.shape)
print(arr2D.shape)

print(arr1D+arr2D)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [12]:
arr1D=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
arr2D=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr1D.shape)
print(arr2D.shape)

print(arr1D+arr2D)

(3, 5)
(2, 5)


ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 