In [2]:
import numpy as np

In [3]:
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x3x2

print(arr3D, arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [4]:
#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

4
9


In [5]:
#slicing
print(arr3D[:,0,:]) #first row from both layer

[[1 2]
 [7 8]]


In [6]:
#slicing
print(arr3D[:,:,0]) #first column from both layer

[[ 1  3  5]
 [ 7  9 11]]


In [7]:
arr3D[:,:,0]=99
print(arr3D)

[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]
