In [1]:
import numpy as np

In [10]:
#Create-from Lists
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [11]:
arr2=np.array([1,2,3,4,5,"phuke"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

['1' '2' '3' '4' '5' 'phuke'] <class 'numpy.ndarray'> <U21 (6,)


In [13]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D,arr2D.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [27]:
#create
arr1=np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((5,)) #prefill
print(arr2,arr2.shape)

arr3=np.full((3,4),100) #prefill with value
print(arr3,arr3.shape)

arr4=np.eye((3)) #identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,11,2) #range felements
print(arr5,arr5.shape)

arr6=np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [32]:
#Properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimension = m,n
print(arr.size) #total element
print(arr.dtype) #data type
print(arr.ndim) #no. of dimension

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
