In [1]:
import numpy as np

# Aggregation

In [7]:
arr=np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.std(arr)) #sigma
print(np.var(arr)) #sigma^2
print(np.median(arr))
print(np.argmax(arr))

15
120
5
1
3.0
4
0
1.4142135623730951
3.0


# Power Functons

In [8]:
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


# Log Functions

In [11]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Rounding

In [13]:
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [15]:
arr=np.array([1,-2,3,-4,5,3,5,1])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-4 -2  1  3  5]
[-4 -2  1  1  3  3  5  5]
[1 2 3 4 5 3 5 1]
